### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by srkds** [srkds/DataStructure-Algo-C#1]

**Comment by Albert-Debbarma** [comment]
1. Fork the Repository by clicking on the symbol at the top right corner.

2. Clone the forked Repository in your local System.

git clone https://github.com/your_user_name/DataStructure-Algo-C.git

3. Create a new Branch:

git branch -YourBranchName-

git checkout -YourBranchName-

4. Make your contributions.

5. Stage your changes and make a commit.

git add .

git commit -m "<your_commit_message>"

6. Push your local commits to the remote Repository.

git push origin -YourBranchName-

7. Create a PR

**Comment by srkds** [comment]
#2
